// Generated by CoffeeScript 1.6.2
(function() {
  var App;

  App = Ember.Application.create();

  App.Router.map(function() {
    return this.resource('locations');
  });

  App.LocationsRoute = Ember.Route.extend({
    model: function() {
      return App.Location.find();
    }
  });

  App.IndexRoute = Ember.Route.extend({
    model: function() {
      return ['red', 'yellow', 'blue'];
    }
  });

  App.IndexController = Ember.ObjectController.extend({
    longitude: 0,
    latitude: 0,
    accuracy: 0,
    heading: 0,
    speed: 0,
    geo: false,
    init: function() {
      if (navigator.geolocation) {
        console.log('Apparently there is geolocation');
        navigator.geolocation.getCurrentPosition(this.geoLocation.bind(this), this.noGeo.bind(this));
        return this.set('geo', true);
      } else {
        console.log('No geolocation - bummer');
        return this.set('geo', false);
      }
    },
    geoLocation: function(location) {
      this.set('latitude', location.coords.latitude);
      this.set('longitude', location.coords.longitude);
      this.set('accuracy', location.coords.accuracy);
      this.set('heading', location.coords.heading);
      this.set('speed', location.coords.speed);
      return console.log('I think I got a position');
    },
    noGeo: function(positionError) {
      console.log('noGeo: Oops!');
      console.log(positionError.message);
      return this.set('status', positionError.message);
    }
  });

  App.LocationsController = Ember.ArrayController.extend();

  App.Store = DS.Store.extend({
    adapter: 'DS.FixtureAdapter'
  });

  App.Location = DS.Model.extend({
    name: DS.attr('string'),
    lat: DS.attr('number'),
    long: DS.attr('number'),
    seen: DS.attr('date')
  });

  App.Location.FIXTURES = [
    {
      id: 1,
      name: "Alice",
      lat: 52.63001,
      long: 1.3010,
      seen: 0
    }, {
      id: 2,
      name: "Bob",
      lat: 52.59231,
      long: 1.2810,
      seen: 0
    }, {
      id: 3,
      name: "Christine",
      lat: 52.6339,
      long: 1.29002,
      seen: 0
    }
  ];

}).call(this);
