// Generated by CoffeeScript 1.6.2
(function() {
  var App;

  App = Ember.Application.create();

  App.Router.map(function() {});

  App.IndexRoute = Ember.Route.extend({
    model: function() {
      return ['red', 'yellow', 'blue'];
    }
  });

}).call(this);
