// Generated by CoffeeScript 1.6.2
(function() {
  var App;

  App = Ember.Application.create();

  App.Router.map(function() {});

  App.IndexRoute = Ember.Route.extend({
    model: function() {
      return ['red', 'yellow', 'blue'];
    }
  });

  App.IndexController = Ember.ObjectController.extend({
    longitude: null,
    latitude: null,
    accuracy: null,
    heading: null,
    speed: null,
    geo: null,
    init: function() {
      if (navigator.geolocation) {
        console.log('Apparently there is geolocation');
        navigator.geolocation.getCurrentPosition(this.geoLocation.bind(this), this.noGeo.bind(this));
        return this.set('geo', true);
      } else {
        console.log('No geolocation - bummer');
        return this.set('geo', false);
      }
    },
    geoLocation: function(location) {
      this.set('latitude', location.coords.latitude);
      this.set('longitude', location.coords.longitude);
      this.set('accuracy', location.coords.accuracy);
      this.set('heading', location.coords.heading);
      this.set('speed', location.coords.speed);
      return console.log('I think I got a position');
    },
    noGeo: function(positionError) {
      console.log('noGeo: Oops!');
      console.log(positionError.message);
      return this.set('status', positionError.message);
    }
  });

}).call(this);
